language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - php -d zend.enable_gc=0 vendor/bin/phpunit -c tests/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

