language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - mkdir -p tests/tmp/cache

script:
  - php vendor/bin/phpunit -c tests/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php:
      - 5.3 
      - hhvm
